[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "flexllmgen"
version = "0.1.7"
description = "Running large language models like OPT-175B/GPT-3 on a single GPU. Focusing on high-throughput large-batch generation."
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
]
dependencies = [
    "torch>=2.9", "transformers>=4.57.3",
    "numpy", "tqdm", "pulp", "attrs",
    "torchvision", "qwen_vl_utils", # qwen-vl
    "protobuf", "sentencepiece", # llava
]
# pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu130
# MAX_JOBS=4 pip install flash-attn --no-build-isolation

[project.urls]
"Homepage" = "https://github.com/FMInference/FlexLLMGen"
"Bug Tracker" = "https://github.com/FMInference/FlexLLMGen/issues"

[tool.setuptools.packages.find]
exclude = ["benchmark*", "dist*", "playground*", "scripts*"]

[tool.wheel]
exclude = ["benchmark*", "dist*", "playground*", "scripts*"]


